In [2]:
import numpy as np

In [3]:
f = np.matrix('1,0,0;0,0,1;0,-1,0')
v = np.matrix('1;2;3')
display(np.dot(f, v))

matrix([[ 1],
        [ 3],
        [-2]])

In [7]:
f = np.matrix('2,1;1,2')
u = np.matrix('1;-1')
v = np.matrix('1;1')
display(np.dot(f, u))
display(np.dot(f, v))
display(u + v)
display(np.dot(f, u + v))
display(np.dot(f, 5*u))

matrix([[ 1],
        [-1]])

matrix([[3],
        [3]])

matrix([[2],
        [0]])

matrix([[4],
        [2]])

matrix([[ 5],
        [-5]])

In [20]:
a = np.matrix('7,2;1,8')
v1 = np.matrix('-2;1')
v2 = np.matrix('1;1')
display(np.dot(a, v1))
display(np.dot(a, v2))

matrix([[-12],
        [  6]])

matrix([[9],
        [9]])

In [21]:
a = np.matrix('-7,6;-12,11')
v1 = np.matrix('1;2')
v2 = np.matrix('1;1')
display(np.dot(a, v1))
display(np.dot(a, v2))

matrix([[ 5],
        [10]])

matrix([[-1],
        [-1]])

In [28]:
c = np.matrix('1,2;2,1')
v1 = np.matrix('1;1')
display(np.dot(c, v1))

matrix([[3],
        [3]])