In [6]:
import numpy as np

In [44]:
x1 = np.array([1,2,1,1])
x2 = np.array([70,130,65,60])

a = np.array([x1, x2])
display('A', a) 
c = np.corrcoef(a)
display('Corr:', c)
eig_val, eig_vec = np.linalg.eig(c)
pca = eig_vec[:,0]
display('Eig val:', eig_val, 'Eig vec:', eig_vec)
display('PCA:', pca)

x1c = x1 - x1.mean()
x1st = x1c / np.dot(x1c, x1c.T)**0.5

x2c = x2 - x2.mean() 
x2st = x2c / np.dot(x2c, x2c.T)**0.5

ast = np.array([x1st, x2st]).T
display('Ast:', ast)

new_x = np.dot(ast, pca)
new_xst = new_x / np.dot(new_x, new_x.T)**0.5
display('new_x:', [round(x, 4) for x in new_xst])

'A'

array([[  1,   2,   1,   1],
       [ 70, 130,  65,  60]])

'Corr:'

array([[1.        , 0.99220261],
       [0.99220261, 1.        ]])

'Eig val:'

array([1.99220261, 0.00779739])

'Eig vec:'

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

'PCA:'

array([0.70710678, 0.70710678])

'Ast:'

array([[-0.28867513, -0.19829369],
       [ 0.8660254 ,  0.85927267],
       [-0.28867513, -0.28642422],
       [-0.28867513, -0.37455475]])

'new_x:'

[-0.244, 0.8643, -0.2881, -0.3323]

In [53]:
cov = np.cov(a)
display(cov)

cov_eig_val, cov_eig_vec = np.linalg.eig(cov)
display(cov_eig_val, cov_eig_vec)

array([[2.50000000e-01, 1.62500000e+01],
       [1.62500000e+01, 1.07291667e+03]])

array([3.88260451e-03, 1.07316278e+03])

array([[-0.99988532, -0.01514395],
       [ 0.01514395, -0.99988532]])